version: '3'
services:
    persontracking:
        build:
            context: ./person_tracking
        container_name: container_persontracking
        working_dir: /code
        ports:
            - 4501:4501
        environment:
            - SOCKET_SERVERIP=host.docker.internal
            - SOCKET_PORT=4501
            - PYTHONUNBUFFERED=1
            - CAM_WIDTH=504
            - CAM_HEIGHT=896
        volumes:
            - "./person_tracking:/code"
        command: ["python", "-u", "server.py"]